version: '3'

services:

 jenkins:
  container_name: jenkins
  build:
   context: jenkins-master
  ports:
   - 8080:8080
   - 50000:50000

 jenkins-slave:
  container_name: jenkins-slave
  build:
   context: jenkins-ant-slave